node src/upgrades/apache.js $(jq -r '.apache' latestVersions.json)
node src/upgrades/base.js dotnet-core $(jq -r '."dotnet-core"' latestVersions.json)
node src/upgrades/elasticsearch.js $(jq -r '.elasticsearch' latestVersions.json)
node src/upgrades/base.js elixir $(jq -r '.elixir' latestVersions.json)
node src/upgrades/base.js erlang $(jq -r '.erlang' latestVersions.json)
node src/upgrades/base.js go $(jq -r '.go' latestVersions.json)
node src/upgrades/jenkins.js $(jq -r '.jenkins' latestVersions.json)
node src/upgrades/base.js jq $(jq -r '.jq' latestVersions.json)
node src/upgrades/kafka.js $(jq -r '.kafka' latestVersions.json)
node src/upgrades/kibana.js $(jq -r '.kibana' latestVersions.json)
node src/upgrades/base.js kotlin $(jq -r '.kotlin' latestVersions.json)
node src/upgrades/logstash.js $(jq -r '.logstash' latestVersions.json)
node src/upgrades/base.js lsof $(jq -r '.lsof' latestVersions.json)
node src/upgrades/memcached.js $(jq -r '.memcached' latestVersions.json)
node src/upgrades/mongo.js $(jq -r '.mongo' latestVersions.json)
node src/upgrades/mysql.js $(jq -r '.mysql' latestVersions.json)
node src/upgrades/neo4j.js $(jq -r '.neo4j' latestVersions.json)
node src/upgrades/nginx.js $(jq -r '.nginx' latestVersions.json)
node src/upgrades/base.js node $(jq -r '.node' latestVersions.json)
node src/upgrades/base.js php $(jq -r '.php' latestVersions.json)
node src/upgrades/base.js python $(jq -r '.python' latestVersions.json)
node src/upgrades/base.js rabbitmqadmin $(jq -r '.rabbitmqadmin' latestVersions.json)
node src/upgrades/rmq.js $(jq -r '.rmq' latestVersions.json)
node src/upgrades/rsyslog.js $(jq -r '.rsyslog' latestVersions.json)
node src/upgrades/base.js ruby $(jq -r '.ruby' latestVersions.json)
node src/upgrades/base.js sbt $(jq -r '.sbt' latestVersions.json)
node src/upgrades/base.js sqlite3 $(jq -r '.sqlite3' latestVersions.json)